services:
  saxo-service:
    build:
      context: .
      dockerfile: StockPriceSheetPrintService/Dockerfile
    container_name: stockPriceSheetPrintService
    restart: unless-stopped
    ports:
      - "5151:5151"
    environment:
      - ASPNETCORE_HTTP_PORTS=5151
      - Saxo__AppKey=${SAXO_OAUTH_APP_KEY}
      - Saxo__AppSecret=${SAXO_OAUTH_APP_SECRET}
      - StockApi__AccessKey=${STOCKAPI_ACCESS_KEY}
      - SheetsApi__SheetsKey=${SHEETSAPI_SHEETS_KEY}
      - Saxo__EncryptionKey=${MY_SECRET_ENCRYPTION_KEY}
      - Saxo__AuthEndpoint=${SAXO_AUTH_ENDPOINT}
      - Saxo__TokenEndpoint=${SAXO_TOKEN_ENDPOINT}
      - Saxo__RedirectUrl=${SAXO_REDIRECT_URL}
      - Saxo__ApiBaseUrl=${SAXO_API_BASE_URL}
      - Discord__Webhook=${DISCORD_WEBHOOK}
      - Discord__WebhookError=${DISCORD_WEBHOOK_ERRORS}
      - Discord__WebhookLogin=${DISCORD_WEBHOOK_LOGIN}

    volumes:
      - ./saxo_data:/app/data  # Her gemmes dit refresh_token.txt permanent på din Pi

    labels:
      - "logging=promtail"

    networks:
      - mix

networks:
  mix:
    external: true
