name: Build and Deploy StockPriceSheetPrintService

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    runs-on: self-hosted
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository
    permissions:
      contents: read
    concurrency:
      group: build-stock-price-sheet-print-service-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup .NET
        uses: actions/setup-dotnet@v6
        with:
          dotnet-version: '10.0.x'
        env:
          DOTNET_INSTALL_DIR: ${{ github.workspace }}/.dotnet

      - name: Build and test
        run: dotnet test --project ArchUnitTest/ArchUnitTest.csproj --configuration Release

  deploy:
    needs: build
    if: github.event_name == 'push'
    runs-on: self-hosted
    permissions: {}
    concurrency:
      group: deploy-stock-price-sheet-print-service
      cancel-in-progress: true

    steps:
      - name: Deploy service
        run: |
          echo "Deploying..."
          cd /home/hjalte/deploy/update
          ./update_stock-price-sheet-print-service.sh
